# Generated by Django 4.2.3 on 2023-08-10 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_alter_hospitaldepartments_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ailment',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
    ]
