# Generated by Django 4.2.3 on 2023-08-12 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0004_alter_appointment_department_and_more'),
        ('course', '0001_initial'),
        ('institution', '0001_initial'),
        ('utilities', '0003_alter_ailment_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ailment',
        ),
        migrations.DeleteModel(
            name='HospitalDepartments',
        ),
        migrations.AlterField(
            model_name='educationinformation',
            name='course_of_study',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='course.course', verbose_name='Course of Study'),
        ),
        migrations.AlterField(
            model_name='educationinformation',
            name='institution',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='institution.institution', verbose_name='Name of Institution'),
        ),
        migrations.DeleteModel(
            name='Course',
        ),
        migrations.DeleteModel(
            name='Institution',
        ),
    ]
