# Generated by Django 4.2.3 on 2023-08-10 17:00

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='completed',
        ),
        migrations.AlterField(
            model_name='appointment',
            name='appointment_date',
            field=models.DateField(help_text='YYYY-MM-DD', verbose_name='Appointment date'),
        ),
        migrations.CreateModel(
            name='DoctorAppointment',
            fields=[
                ('pkid', models.BigAutoField(editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symptoms', models.TextField()),
                ('recommendation', models.TextField()),
                ('drugs', models.TextField()),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='appointment', unique=True)),
                ('appointment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
