# Generated by Django 4.2.3 on 2023-08-10 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0002_alter_hospitaldepartments_options_and_more'),
        ('appointments', '0002_remove_appointment_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappointment',
            name='ailment',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.ailment'),
        ),
    ]
