# Generated by Django 4.2.3 on 2023-08-12 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ailment', '0001_initial'),
        ('appointments', '0004_alter_appointment_department_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='ailment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ailment.ailment'),
        ),
    ]
