# Generated by Django 4.2.3 on 2023-08-12 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ailment', '0001_initial'),
        ('appointments', '0005_alter_doctorappointment_ailment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorappointment',
            name='ailment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ailment.ailment'),
        ),
    ]
